version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"


# docker compose up 실행
# docker compose up -d 백그라운드 실행
# docker compose stop 정지
# docker compose down 삭제